#!/usr/bin/python3

print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('<meta charset="UTF-8">')
print('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
print('<link rel="icon" type="image/x-icon" href="/icons/favicon.ico">')
print('<link rel="stylesheet" href="/assets/css_files/styles.css">')
print('<title>upload via cgi</title>')
print('</head>')
print('<body>')
print('<section class="title">')
print('<a href="/">')
print('<h1 class="title">Webserv</h1>')
print('</a>')
print('</section>')
print('<section class="block">')
print('<h2>Upload a file via CGI</h2>')
print ('<label for="myFilePicker">Select a file:</label>')
print ('<iframe name="hiddenFrame" style="display:none;"></iframe>')
print ('<form  method = "post" enctype="multipart/form-data" target="hiddenFrame" onsubmit="sendPost();return false;" >')
print ('<input type="file" id="myFilePicker" name="myFilePicker">')
print ('<input type = "submit" value = "Submit"/>')
print ('</form>')
print ('<p id="uploadResult" style="margin-top: 1em;"></p>')
print ('</section>')
print ('</body>	')
print ('</html>')

print ('<script>')
print ('function sendPost() {')
print ('const fileInput = document.getElementById("myFilePicker");')
print ('const file = fileInput.files[0];')
print ('if (!file) {')
print ('document.getElementById("uploadResult").innerText = "❌ Please select a file.";')
print ('return;')
print ('}')
print ('const formData = new FormData();')
print ('formData.append("myFilePicker", file);')
print ('fetch("/cgi-bin/file_upload2.py", {')
print ('method: "POST",')
print ('body: formData')
print ('})')
print ('.then(response => {')
print ('return response.text().then(text => {')
print ('if (response.ok) {')
print ('document.getElementById("uploadResult").innerText = "✅ File send";')
print ('} else {')
print ('document.getElementById("uploadResult").innerText = "❌ Error ${response.status} : ${text}";')
print ('}')
print ('fileInput.value = "";')
print ('});')
print ('})')
print ('.catch(error => {')
print ('document.getElementById("uploadResult").innerText = "❌ Error network : " + error;')
print ('});')
print ('}')
print ('</script>')