#!/usr/bin/python3

print ('<html>')
print ('<head>')
print ('<meta charset="UTF-8">')
print ('<meta name="viewport" content="width=device-width, initial-scale=1.0">')	
print ('<title>File upload</title>')
print ('</head>')
print ('<body style="background-color: #bee8fd;">')
print ('<section>')
print ('<div class="container" style="text-align: center; margin-top: 6em; font-family: Calibri; font-size: 20px; line-height: 1.5; padding: 2em; border: 1px solid #ccc; border-radius: 5px; background-color: #f9f9f9; box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);">') 
print ('<h3>Silly goofy file upload</h3>')
print ('<img src="/assets/dog-rainy-dog.gif" alt="dog" style="display:block; margin:auto; max-width:300px; max-height:300px;">')
print ('<p>(me irl btw)</p>')
print ('<label for="myFilePicker">Please select a file:</label>')
print ('<form  method = "post" enctype="multipart/form-data" action = "/cgi-bin/file_upload.py">')
print ('<input type="file" id="myFilePicker" name="filePicker">')
print ('<input type = "submit" value = "Submit" />')
print ('</form>')
print ('<form  method = "post" action = "/index.html">')
print ('<button name="goto_index" value="teleport">Go back to main page</button>')
print ('</form>')
print ('</div>')
print ('</section>')
print ('</body>	')
print ('</html>')